name: Sync wiki documentation

on:
  push:
    branches:
      - main
    paths:
      - '.github/wiki/**'
  repository_dispatch:
    types: [docs]
  gollum:

env:
  REPO_PATH: '.github/wiki'
  WIKI_PATH: 'wiki'
  GIT_USERNAME: 'github-actions[bot]'
  GIT_EMAIL: 'github-actions@github.com'
  GIT_COMMIT_MESSAGE: 'docs: Bidirectional sync between docs and wiki'

jobs:
  sync-docs-to-wiki:
    if: github.repository == 'SystemJAADE/healthy-patients-service' && github.event_name != 'gollum'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Push files into wiki repo
        uses: newrelic/wiki-sync-action@main
        with:
          source: ${{ env.REPO_PATH }}
          destination: ${{ env.WIKI_PATH }}
          branch: main
          token: ${{ secrets.HEALTHY_REPO_TOKEN }}
          gitAuthorName: ${{ env.GIT_USERNAME }}
          gitAuthorEmail: ${{ env.GIT_EMAIL }}
          commitMessage: ${{ env.GIT_COMMIT_MESSAGE }}

  sync-wiki-to-docs:
    if: github.repository == 'SystemJAADE/healthy-patients-service' && github.event_name == 'gollum'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master

      - name: Push files into repo
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: ${{ env.REPO_PATH }}
          branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
          gitAuthorName: ${{ env.GIT_USERNAME }}
          gitAuthorEmail: ${{ env.GIT_EMAIL }}
          commitMessage: ${{ env.GIT_COMMIT_MESSAGE }}
